services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "9090:8080"
    command: start-dev



  prometheus:
    image: prom/prometheus:v2.51.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus/prometheus-local-app.yml:/etc/prometheus/prometheus.yml:ro
      - local_app_prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3001:3000"
    volumes:
      - local_app_grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

volumes:
  local_app_postgres_data:
  local_app_prometheus_data:
  local_app_grafana_data:
