apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: {{ .Release.Name }}-keycloak
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-keycloak
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: {{ .Values.keycloak.service.nodePort }}
