apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: {{ .Release.Name }}-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-keycloak
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          args:
            - start-dev
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.auth.adminUser | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.auth.adminPassword | quote }}
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-backend-postgresql:5432/keycloak"
            - name: KC_DB_USERNAME
              value: postgres
            - name: KC_DB_PASSWORD
              value: postgres
          ports:
            - containerPort: 8080
              name: http
          startupProbe:
            httpGet:
              path: /realms/master
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /realms/master
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /realms/master
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
